### ISSUE TITLE
[Bug] in main.js: Chain.validateChain()

### ISSUE THREAD

**Issue by leozvoy** [ycraaron/LuotuoCoin#1]
在 **Chain.validateChain()** 中：
    需要增加：**验证当前block的hash是否以difficulty个'0'开头**。
    否则可篡改当前block的data，再使用Block.computeHash()生成hash，从而避开POW，迅速生成一个非法新链。
    支持B站未来的百万粉UP主 :)

**Comment by ycraaron** [comment]
应该不需要这个验证。因为难度是可变的，如果在计算出来的时候难度是4，然后后面难度变成5，这个条件永远都不成立了。
然后`篡改当前block的data，再使用Block.computeHash()生成hash，从而避开POW，迅速生成一个非法新链。`这个会使得区块链前后断裂，validateChain不会通过的。

**Comment by leozvoy** [comment]
@ycraaron 
是这样的，我在每个区块里都记录了这个区块添加进链时的难度，验证的时候也是从区块里读取难度，因此当链的难度改变时，不会影响对已生成区块的验证哈
然后的话，可能是我没表达清楚:joy:，我的意思是，如果有人恶意在当前链的最后一个区块接着挖矿，但他挖的时候把难度改成0，或者他把链的难度篡改成0了，大家都在用当前的难度挖，挖得很慢，但是这个人可以很快挖出来新的区块，并且他挖出来的区块除了难度不一样，其他和正常挖的区块没任何区别啊，所以我感觉需要对难度进行验证。是我想的不对吗，还是我漏掉了什么:sweat_smile:
感谢落拓的回复，我只是确实没想通这一点，非杠

**Comment by ycraaron** [comment]
本来我想的是，这个block在之后的验证环节，其他节点会reject掉。但是如果验证环节里没有和当前难度做验证，也没有拒绝的标准了。所以如果真的通过reverse enginner改了内存把难度改掉了，那么确实可以出现这样的情况。addblock的时候，链应该验证一下这个hash是否符合难度。我想去看看bitcoin是怎么实现的。。。

**Comment by ExcaliburEX** [comment]
学会了README中的shields.io:smile:，用Travis CI什么的太麻烦了

**Comment by leozvoy** [comment]
看了下README才发现《视频 4-2: 向区块链中添加数字签名》，这个视频B站好像没有呀

**Comment by ycraaron** [comment]
@

> 看了下README才发现《视频 4-2: 向区块链中添加数字签名》，这个视频B站好像没有呀

最新投稿 在审核
