### ISSUE TITLE
合作开发

### ISSUE THREAD

**Issue by ShengYu2030** [ycraaron/LuotuoCoin#9]
落拓你好，麻烦QQ邮箱回复我一下。

**Comment by Anonymous-Joker** [comment]
你好，哪位，什么事



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月17日(周日) 晚上7:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ycraaron/LuotuoCoin] 合作开发 (Issue #9)




 
落拓你好，麻烦QQ邮箱回复我一下。

**Comment by ShengYu2030** [comment]
之前发给你QQ邮箱了，你没有回复我。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Anonymous-Joker ***@***.***&gt;
发送时间: 2024年3月17日 19:14
收件人: ycraaron/LuotuoCoin ***@***.***&gt;
抄送: ShengYu2030 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ycraaron/LuotuoCoin] 合作开发 (Issue #9)





 你好，哪位，什么事 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年3月17日(周日) 晚上7:12 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [ycraaron/LuotuoCoin] 合作开发 (Issue #9) 
 
 
 
 
   
 落拓你好，麻烦QQ邮箱回复我一下。

**Comment by ShengYu2030** [comment]
落拓你好


给你写邮件的目的是邀请你作为联合创始人加入资产币（暂时命名为资产币）的开发团队。

&nbsp;

你不是区块链开发人员为什么邀请你?

看中你的综合能力。包括但不限于英语水平，编程能力，表达交流能力，你年纪在30岁左右，在我看来既具备了一定的知识储备和经验，又具有较强的学习能力。我看过你的视频“比特币区块链基础概念和简单实现”认为你有一定的区块链基础，如果你愿意花时间和精力，我认为你可以对区块链有全面深入的了解，有能力开发资产币。综上所述认为你是理想的成员之一。

&nbsp;

有很多的相关问题。比如你我在团队中的作用，项目的开发周期等等，这里不做深入说明。

&nbsp;

文件是关于资产币简述的文档。

&nbsp;

下面是一些个人的见解

关于落拓的全能教室的一篇笔记（比特币里的公钥public key和地址public address的区别？为什么应该避免重用地址？）

我说明几点。笔记中，“只要你从来没用这个地址花过钱，那么如果有人想要盗取你这个地址上的钱，不仅需要破解ec这个算法，还要再破解hash。”如果破解ec算法非常快，这种方式就不能提供保护。攻击方法如下，从比特币交易池中获取没有确认过的交易，因为交易池含有账户公钥，因此只要破解ec不需要破解hash。如果在短时间内能破解ec就能再发起一笔交易将账户中的钱用提高手续费的方式转移到指定账户。由于矿工是优先采用手续费高的，因此采用这种方式，可以实施攻击。因此不重用地址并不完全等于多一层hash保护。

不要重复使用地址可以使比特币具有一定的匿名性。如果重复使用地址的话，和你交易过的人。可以以后通过区块链浏览器查询到地址所剩比特币的余额。这相当于我银行给你转账以后。你可以实时查询我该银行账号下的余额，这显然不利于彼此双方的隐私。比特币钱包生成新的地址，可以在一定程度上保护了交易双方的隐私。因此在隐私保护方面考虑，每次更换地址很有必要。

&nbsp;

&nbsp;

牛顿说过一句话“如果我看得更远，那是因为我站在巨人的肩膀上。”（"If I have seen further, it is by standing on the shoulders of giants."）中本聪在前人的基础上整合创新取得了成功，而我们也可以在中本聪等人的基础上进一步创新并取得成功。

&nbsp;

创建团队本质上是一个双向选择的过程。如果您对此感兴趣，欢迎与我联系以便进行深入的交流。

&nbsp;




AMD-2017
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ycraaron/LuotuoCoin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月17日(星期天) 晚上7:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ycraaron/LuotuoCoin] 合作开发 (Issue #9)





 你好，哪位，什么事 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年3月17日(周日) 晚上7:12 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [ycraaron/LuotuoCoin] 合作开发 (Issue #9) 
 
 
 
 
   
 落拓你好，麻烦QQ邮箱回复我一下。
